---
title: "Aplicaciones de modelos de selección"
author: "Irvin Rojas"
institute: "CIDE"
date: "22 de septimebre de 2020"
mathspec: true
output:
  xaringan::moon_reader:
    seal: false
    chakra: "https://remarkjs.com/downloads/remark-latest.min.js"
    lib_dir: libs
    nature:
      highlightLines: true
      countIncrementalSlides: false
      titleSlideClass: ["middle", "center"]
      ratio: "16:9"
      beforeInit: ["https://platform.twitter.com/widgets.js", "libs/cols_macro.js"]
      navigation:
      scroll: false
    css: [default, "libs/cide.css", metropolis-fonts, "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap-grid.min.css", "https://use.fontawesome.com/releases/v5.7.2/css/all.css", "https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css"]
include-before:
- '\newcommand\myeq{\stackrel{\mathclap{\normalfont\mbox{s}}}{~}}'

---
class: title-slide

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = "figures/")

library(tidyverse)
library(pacman)
library(janitor)
library(sandwich)
library(modelsummary)
#library(nnet)
#library(mlogit)
p_load(tidyverse, foreign, reshape2, psych, qwraps2, forcats, readxl, 
       broom, lmtest, margins, plm, rdrobust, multiwayvcov,
       wesanderson, sandwich, stargazer,
       readstata13, pscore, optmatch, kdensity, MatchIt, bootstrap, matlib, dplyr)

xfun::pkg_load2(c('base64enc', 'htmltools', 'mime'))

```

```{css, echo = FALSE}
.huge .remark-code { /*Change made here*/
  font-size: 200% !important;
}
.tiny .remark-code { /*Change made here*/
  font-size: 60% !important;
}

```


.title[
# Sesión 11. Aplicaciones de modelos de selección
]
.subtitle[
## Econometría II
]
.author[
### Irvin Rojas <br> [rojasirvin.com](https://www.rojasirvin.com/) <br> [<i class="fab fa-github"></i>](https://github.com/rojasirvin) [<i class="fab fa-twitter"></i>](https://twitter.com/RojasIrvin) [<i class="ai ai-google-scholar"></i>](https://scholar.google.com/citations?user=FUwdSTMAAAAJ&hl=en)
]

.affiliation[
### Centro de Investigación y Docencia Económicas <br> División de Economía
]

---

class: inverse, middle, center

# Tobit

---

# Tobit

- Zou, B., & Luo, B. (2019). Rural Household Energy Consumption Characteristics and Determinants in China. Energy.

- El consumo de energía representa un importante componente del gasto

- Nos interesa conocer qué factores afectan el consumo energético

- $y_i^j$ consumo de tipo de combustible $j$ en el hogar $i$

- Tenemos $K$ características de los hogares

- El interés es ver el efecto de un cambio en $x_{k}$ sobre la participación de cada tipo de energia $j$

---

# Censura

- Muchos de los hogares tienen cero en el consumo de algunos tipos de combustible

- Se reportan los coeficientes estimados y los efectos marginales

- Podemos internalizar esta decisión en un modelo microeconómico donde el consumo cero es el resultado de un proceso de optimización


---

class: inverse, middle, center

# Heckman

- Hipótesis Roy/Borjas

  - Las desigualdades entre los países determinan la selección de los migrantes

- Los migrantes comparan lo que podrían ganar en el país de nacimiento


---

# Dos ecuaciones

- Selección:


- Resultados:


---

# Estimación

- Requerimos que al menos una variable esté omitida de la ecuación de resultados (segunda etapa)

- Hay algunos autores que a esta variable excluída la llaman **instrumento** por las razones que quedarán claras más adelante

- Conjunto de características demográficas se incluyen en ambas etapas

- Hay un instrumento, las becas ERASMUS, 

---

# Modelos en dos etapas de Heckman

- Parey, M., Ruhose, J., Waldinger, F., & Netz, N. (2017). The selection of high-skilled emigrants. *Review of Economics and Statistics*, 99(5), 776-792.

---

class: inverse, middle, center

# Modelo en dos partes

---

# Modelo en dos partes

- Colchero, M. A., Molina, M., & Guerrero-López, C. M. (2017). After Mexico implemented a tax, purchases of sugar-sweetened beverages decreased and water increased: difference by place of residence, household composition, and income level. *The Journal of nutrition*, 147(8), 1552-1557.

- En México hay un problema de salud asociado al consumo de bebidas azucaradas

- Problema de salud pública: ¿sirven los impuestos para reducir el consumo de bebidas azucaradas?

- Datos de la ENIGH que tiene datos de ingresos y gastos de los hogares

---

# Modelo en dos partes

- El cero es un cero verdadero resultado de un proceso de optimización

- Primera parte: consumo positivo de bebidas azucaradas con un modelo Probit

- Segunda parte: modelo lineal para las familias con compras positivas

- Se comparan las tendencias esperadas vs las tendencias realizadas después de la implementación de un impuesto

- Los resultados indican que el consumo de bebidas azucaradas efectivamente disminuyó 2% después de la implementación del impuesto

- Además, hay evidencia de un incremento de 3% en la compra de agua embotellada

---

class: inverse, middle, center

# Modelo ordenado con selección

---

# Modelo ordenado con selección

- **Ordenado + selección**: Alemi, F., Circella, G., Mokhtarian, P., & Handy, S. (2019). What drives the use of ridehailing in California? Ordered probit models of the usage frequency of Uber and Lyft. *Transportation Research Part C: Emerging Technologies*, 102, 233-248.

- ¿Cómo varía el uso de serivicios de viajes individuales tipo Uber debido a las características de las personas y los lugares donde viven?

- Datos en panel de California de millenials y generación X

- Frecuencia de uso en tres categorías: nunca (0), con poca frecuencia (1) y con mucha frecuencia (2)

- Tenemos un elemento de selección o adopción: vemos muchos ceros por usuarios que nunca usan los servicios
  - Estos son los ceros estructurales

---

# Modelos

- Modelo probit ordenado inflado en cero

  - Variable frecuencia observada
    - Vemos también ceros como resultado 
    
- Modelo probit ordenado con selección de muestra

  - Extensión del modeo de Heckman en dos partes visto en clase
  
  - Se formulan dos procesos diferentes con errores correlacionados
  
     - Adopción
     - Frecuencia

- El OPSS reescala los resultados por la probabilidad de tener ceros estructurales

- El ZIOPC
  

---

# Resultados

- Los aspectos sociodemográficas determinan la adopción, pero no la frecuencia

- La frecuencia está determinada sobre todo por las características de las ciudades

- Los dos modelos son consistentes entre sí
  
- [Liga a la presentación](https://slides.com/dave6788/ecnii/fullscreen)


---

# Próxima sesión

- Estudiaremos variables instrumentales

- W, Capítulo 5

- CT, Capítulo 4 (secciones 4.8 y 4.9)

- Algunas aplicaciones recientes se pueden encontrar en estos trabajos:

  - Hackett, L., & Marquez-Padilla, F. (2019). Working for Change: the Effect of Female Labor Force Participation on Fertility. SSRN Working Paper 3354753.
  - Campos-Vazquez, R. M., & Nuñez, R. (2019). Obesity and labor market outcomes in Mexico/Obesidad y el mercado de trabajo en México. *Estudios Económicos*, 34(2), 159-196.
  - López-Feldman, A., & Chávez, E. (2017). Remittances and natural resource extraction: Evidence from Mexico. *Ecological Economics*, 132, 69-79.
  - Mocetti, S. (2007). Intergenerational earnings mobility in Italy. *The BE Journal of Economic Analysis & Policy*, 7(2).  
 - Hirvonen, K., & Hoddinott, J. (2017). Agricultural production and children's diets: Evidence from rural Ethiopia. *Agricultural Economics*, 48(4), 469-480.


---

class: center, middle

Presentación creada usando el paquete [**xaringan**](https://github.com/yihui/xaringan) en R.

El *chakra* viene de [remark.js](https://remarkjs.com), [**knitr**](http://yihui.org/knitr), y [R Markdown](https://rmarkdown.rstudio.com).

Material de clase en versión preliminar.

**No reproducir, no distribuir, no citar.**
