---
title: "Más allá de MCO"
author: "Irvin Rojas"
institute: "CIDE"
date: "18 de agosto de 2020"
output:
  xaringan::moon_reader:
    seal: false
    chakra: "https://remarkjs.com/downloads/remark-latest.min.js"
    lib_dir: libs
    nature:
      highlightLines: true
      countIncrementalSlides: false
      titleSlideClass: ["middle", "center"]
      ratio: "16:9"
      beforeInit: ["https://platform.twitter.com/widgets.js", "libs/cols_macro.js"]
      navigation:
        scroll: false
    css: [default, "libs/cide.css", metropolis-fonts, "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap-grid.min.css", "https://use.fontawesome.com/releases/v5.7.2/css/all.css", "https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css"]

---
class: title-slide

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = "figures/")
library(tidyverse)
library(magick)
library(reticulate)
xfun::pkg_load2(c('base64enc', 'htmltools', 'mime'))
```

.title[
# Sesión 1. Más allá de MCO
]
.subtitle[
## Econometría II
]
.author[
### Irvin Rojas <br> [rojasirvin.com](https://www.rojasirvin.com/) <br> [<i class="fab fa-github"></i>](https://github.com/rojasirvin) [<i class="fab fa-twitter"></i>](https://twitter.com/RojasIrvin) [<i class="ai ai-google-scholar"></i>](https://scholar.google.com/citations?user=FUwdSTMAAAAJ&hl=en)
]

.affiliation[
### Centro de Investigación y Docencia Económicas <br> División de Economía
]

---
# Agenda

1. Presentación mía y de ustedes

1. Descripción general del curso

1. ¿Qué cosas distintas veremos con respecto a Econometría I?

1. ¿Qué utilidad tiene el curso en su formación?

1. ¿Qué tipo de preguntas y datos son relevantes para la investigación empírica?

---

# Descripción general del curso

1. Logística del curso

1. Evaluación

1. Tareas

1. Laboratorios<

1. Presentaciones

1. Usemos **Microsoft Teams** casi para todo

---

# Más allá de MCO

- ¿Cómo es la econometría de los libros de texto con los que aprendí econometría?

  - Modelos macro con una larga lista de variables *explicativas*
  
  - Funciones de producción micro o macro
  
  - Se enumeran una serie de supuestos de consistencia
  
  - Se enumeran posibles formas de violación a los supuestos y formas de resolver el problema
  

- La econometría que veremos en este curso se enfoca menos en *modelar* y más en técnicas para resolver preguntas específicas del tipo $x \rightarrow y$

  - No se piensa tanto en *el modelo*
  
  - Los econometristas usan el término *estrategia de identificación*
  
  - Identificación: medir

---

# Ruta típica

$$y=\alpha+\beta x + \varepsilon$$
- Damos supuestos sobre cómo son los errores con respecto a $x$

- No se especifica si es una relación causal o si estamos parametrizando la media condicional

- Se asume homocedasticidad, que no hay multicolinealidad y regresores fijos

- Resulta que $\beta" es insesgado y el *BLUE*

- Recurrimos a primeros auxilios en caso de autocorrelación, heterocedasticidad o multicolinealidad

---

# En este curso

- Nos enfocaremos en formas de estimar relaciones cuando los supuestos de MCO no se cumplen

- Resolveremos el problema de estimar modelos cuando las variables dependientes no son continuas (por ejemplo, para estudiar la probabilidad de ocurrencia de un evento o la cantidad de eventos que ocurren en un intervalo de tiempo)

- Luego nos enfocaremos en métodos para resolver los problemas asociados con $E(u|X)$

- Trataremos de aterrizar todas las discusiones con aplicaciones empíricas modernas de temas muy variados

- Cerraremos con la introducción a metodologías ampliamente usadas en la investigación aplicada

---

# Ejemplo: función de salario

.pull-left[
- Primeros cursos de econometría

  - Se busca modelar el ingreso laboral de un individuo
  
  - $X$ incluiría características del individuo, la escuela, la familia, la clase, los compañeros, ...
  
  - Se hacen recomendaciones basadas en los signos de los coeficientes
]

.pull-right[
- Econometría en este curso

  - No importa tanto *explicar* $y$
  
  - Nos enfocamos más en la relación (posiblemente el efecto) de $x_i$ en $y$
  
  - Por ejemplo, ¿cómo afecta el tipo de escuela?
  
  - Se busca eliminar el *sesgo de selección*

  - Es decir, sabemos que los individuos que acceden a educación privada son diferentes (padres, ambiente del hogar, nutrición)
  
  - $y_i$ está determinada por estos factores
]
---

# Papel de las $X$

- Econometría introductoria

  - Son parte de *el modelo*
  
- Econometría en este curso

  - Las entendemos como *controles*: factores que podrían *confundir* el efecto de $x$ en $y$
  
  - Un vector $X_i$ que al condicionar sobre estas variables comparamos individuos comparables:
  
  $$E(u_i|privada_i,X_i)=E(u_i|X_i)$$
  - Lo cual es menos débil que el $E(u_i|privada_i,X_i)=0$
  
  - Asumiendo linealidad tenemos la siguiente regresión:
  
  $$y_i=\alpha+ privada_i \beta+\gamma'X_i+u_i$$
  
  - Al *controlar* hacer comparaciones dentro de grupos de unidades parecidas
  
---

# Textos

- Usaremos libros de texto que hacen un buen balance entre teoría y aplicaciones, pero que no son textos teóricos

- Hayashi (2010) es la opción para quienes quieren adentrarse a los detalles teóricos más profundos

- Veremos muchas aplicaciones empíricas recientes

- De estas lecturas es posible que alguien saque tema de tesis

---

# Características principales de los datos

- Nivel de agregación mucho más fino

- Alto grado de heterogeneidad (por ejemplo, ingreso)

- Mucha variabilidad

- Variables dependientes categóricas, censauradas, de conteo, etc

- Dimensión temporal

- **Queremos ligar directamente los datos con teoría económica**

---

# La teoría y los datos

.pull-left[
**Forma reducida**

- Relación entre variables de respuesta $y$ condicional a las variables que se asumen como exógenas $X$

- Es (casi) imposible modelar todas las relaciones de dependencia

- Nos dan efectos de *primer orden*

- Podemos relacionar estos efectos directamente con los ejercicios de estática comparativa de un modelo
]

.pull-right[
**Modelos estructurales**

- Estimación de los parámetros que caracterizan las preferencias o la tecnologúa

- Se asumen formas específicas para las funciones de utilidad, de costos, de producción y sobre la distribución de los errores

- Permiten realizar *experimentos* que toman en cuenta las interrelaciones entre las variables
]

---

class: center, middle

Presentación creada usando el paquete [**xaringan**](https://github.com/yihui/xaringan) en R.

El *chakra* viene de [remark.js](https://remarkjs.com), [**knitr**](http://yihui.org/knitr), y [R Markdown](https://rmarkdown.rstudio.com).

Material de clase en versión preliminar.

**No reproducir, no distribuir, no citar**