---
title: "Extensiones con datos en panel"
author: "Irvin Rojas"
institute: "CIDE"
date: "13 de octubre de 2020"
mathspec: true
header-includes:
  - \usepackage{amsmath}
output:
  xaringan::moon_reader:
    seal: false
    chakra: "https://remarkjs.com/downloads/remark-latest.min.js"
    lib_dir: libs
    nature:
      highlightLines: true
      countIncrementalSlides: false
      titleSlideClass: ["middle", "center"]
      ratio: "16:9"
      beforeInit: ["https://platform.twitter.com/widgets.js", "libs/cols_macro.js"]
      navigation:
      scroll: false
    css: [default, "libs/cide.css", metropolis-fonts, "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap-grid.min.css", "https://use.fontawesome.com/releases/v5.7.2/css/all.css", "https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css"]
include-before:
- '\newcommand\myeq{\stackrel{\mathclap{\normalfont\mbox{s}}}{~}}'

---
class: title-slide

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = "figures/")

library(tidyverse)
library(pacman)
library(janitor)
library(sandwich)
library(modelsummary)
#library(nnet)
#library(mlogit)
p_load(tidyverse, foreign, reshape2, psych, qwraps2, forcats, readxl, 
       broom, lmtest, margins, plm, rdrobust, multiwayvcov,
       wesanderson, sandwich, stargazer,
       readstata13, pscore, optmatch, kdensity, MatchIt, bootstrap, matlib, dplyr)

xfun::pkg_load2(c('base64enc', 'htmltools', 'mime'))

```

```{css, echo = FALSE}
.huge .remark-code { /*Change made here*/
  font-size: 200% !important;
}
.tiny .remark-code { /*Change made here*/
  font-size: 60% !important;
}

```


.title[
# Sesión 17. Extensiones con datos en panel
]
.subtitle[
## Econometría II
]
.author[
### Irvin Rojas <br> [rojasirvin.com](https://www.rojasirvin.com/) <br> [<i class="fab fa-github"></i>](https://github.com/rojasirvin) [<i class="fab fa-twitter"></i>](https://twitter.com/RojasIrvin) [<i class="ai ai-google-scholar"></i>](https://scholar.google.com/citations?user=FUwdSTMAAAAJ&hl=en)
]

.affiliation[
### Centro de Investigación y Docencia Económicas <br> División de Economía
]

---

# Agenda

- Abrir la posibilidad a problemas de endogeneidad en panel

- Introducir modelos con dependencia temporal (dinámicos)

- Breve introducción a diferencia en diferencias

---

class: inverse, middle, center

# Variables instrumentales con panel 

---

# Variables instrumentales con panel

- Consideremos el modelo sin efectos individuales

$$y_{it}=X_{it}\beta+u_{it}$$
- Asumimos independencia entre las $i$ y que nuestro panel es *corto* y con $N\to\infty$

- Ahora, apilamos las observaciones

$$\mathbf{y}_i=\mathbf{X}_i\beta+\mathbf{u}_i$$
donde $\mathbf{y}_i$ y $\mathbf{u}_i$ son vectores de $T\times 1$ para cada individuo $i$ y $\mathbf{X}_i$ es una matriz de $T\times K$


---

# Instrumentos

- Supongamos que existe una matriz de $T\times r$ de instrumentos llamada $Z_i$, con $r\geq K$ siendo el número de instrumentos

- Supongamos la condición de momentos
$$E(\mathbf{Z}_i'\mathbf{u}_i)=\mathbf{0}$$
- Entonces, podemos plantear un problema de momentos:

$$Q_N(\beta)=\left(\sum_i\mathbf{Z}_i'\mathbf{u}_i\right)'\mathbf{W}_N\left(\sum_i\mathbf{Z}_i'\mathbf{u}_i\right)$$

---

# Estimador de panel por MGM

- Y la solución al problema nos da el estimador de panel por MGM

$$\hat{\beta}_{MGM,Panel}=\left(\left(\sum_i\mathbf{X}_i'\mathbf{Z}_i\right)\mathbf{W}_N\left(\sum_i\mathbf{Z}_i'\mathbf{X}_i\right)\right)^{-1} \left(\sum_i\mathbf{X}_i'\mathbf{Z}_i\right)\mathbf{W}_N\left(\sum_i\mathbf{Z}_i'\mathbf{y}_i\right)$$
--

- La condición de consistencia es que la condición de momentos se cumpla

--

- La varianza del estimador será

$$\hat{V}(\hat{\beta}_{MGM,Panel})=(X'ZW_NZ'X)^{-1}X'ZW_N(N\hat{S})W_N'Z'X(X'ZW_NZ'X)^{-1}$$

donde, como siempre $\hat{S}$ es un estimador consistente de $S=p\lim\frac{1}{N}\sum_iZ_i'u_iu_i'Z_i$
---

# Estimación

- Podemos implementar dos tipos de estimadores, dependiendo de la forma que se le da a $W_N$

--

- **Estimador de mínimos cuadrados en dos etapas** o **estimador de MGM en un paso**: $W_N=(Z'Z)^{-1}$
  
- En este caso, el estimador de MGM de panel es

$$\hat{\beta}_{MC2E}=(X'Z(Z'Z)^{-1}Z'X)^{-1}(X'Z(Z'Z)^{-1}Z'y)$$

- No se confundan con los nombres

  - Se le llamama de MC2E porque lo podemos obtener, como ya hemos mostrado varias veces, primero obteniendo $\hat{X}_i$ y luego estimando la regresión de $y_i$ sobre estos valores ajustados (aunque nunca hagamos esto en la práctica)
  
  - También se le llama de un paso porque se puede obtener simplemente haciendo $W_N=(Z'Z)^{-1}$ en un solo paso
  
- La matriz de varianzas robusta es $\hat{V}(\hat{\beta}_{MGM,Panel})$, con $W_N=(Z'Z)^{-1}$
  
---

# Estimación

- **Estimador de MGM en dos pasos**: $W_N=\hat{S}^{-1}$

- Habíamos hablado sobre este procedimiento en la [Sesión 13](https://rojasirvin.github.io/ECNII2020/sesiones/s13/sesion13.html#18), cuando introdujimos MGM

  - En un primer paso se obtiene $\beta$ y se obtiene los residuales $\hat{u}_i$ para calcular $\hat{S}=\frac{1}{N}Z_i'\hat{u}_i\hat{u}_i'Z_i$
  
  - Obtener $\hat{\beta}_{MGMDP}=\left(X'Z\hat{S}^{-1}Z'X\right)^{-1}X'Z\hat{S}^{-1}Z'y$ y $\hat{V}(\hat{\beta}_{MGMDP})=\left(X'Z(N\hat{S})^{-1}Z'X\right)^{-1}$
  
- Este estimador es el más eficiente


---

# Ganancias de eficiencia

- Supongamos exogeneidad estricta de $X$, por lo que $Z=X$

- Aún en este caso podríamos incrementar la eficiencia del estimador al incluir en $Z$ a funciones de $X$ (por ejemplo, potencias) o sus valores rezagados

- Por esta razón, al estimador de MGM en dos pasos no le llamamos el estimador óptimo

---

# Selección de instrumentos

- Los resultados anteriores asumen la existencia de la matriz de instrumentos $Z_i$ de $T\times r$

- Recordemos que la condición para identificación es $E(Z_i'u_i)=0$

- Tendremos más instrumentos entre más supuestos estemos dispuestos a hacer sobre las correlaciones entre $u_{it}$ y $z_{is}$

- A estos supuestos se les llama **supuestos de exogeneidad**


---

# Exogeneidad contemporánea

- Asume que los instrumentos están contemporáneamente no correlacionados con el error

$$E(z_{it}u_{it})=0,\quad\quad t=1,\ldots,T$$

- Tenemos $Tr$ condiciones de momentos:
  
$$Z_i=\begin{pmatrix}z_{i1}' &  0 & \cdots & 0 \\0 &  z_{i2}' && \vdots \\\vdots & & \ddots & 0 \\0 & \cdots & 0 &z_{iT}'\\\end{pmatrix}$$

---

# Exogeneidad débil

- Podemos usar los valores predeterminados (pasados) como instrumentos

- Asumimos que estos valores rezagados están no correlacionados con el error contemporáneo

$$E(z_{is}u_{is})=0,\quad\quad s\leq t,\quad t=1.\ldots,T$$

---

# Exogeneidad fuerte

- Podemos usar los valores pasados y futuros como instrumentos al asumir que no están correlacionados con el error contemporáneo

$$E(z_{is}u_{is})=0,\quad\quad s,t=1.\ldots,T$$

---

class: inverse, middle, center

# Heterogeneidad no observada y endogeneidad

---

# Heterogeneidad no observada

- Consideremos ahora el modelo con efectos fijos correlacionados y donde algunos regresores son endógenos

$$y_{it}=\alpha_i+x_{it}'\beta++\varepsilon_{it}$$

- El error en este caso será $\alpha_i+\varepsilon{it}$ y el estimador de MCO será incosistente porque $E(x_{it}(\alpha_i+\varepsilon{it}))\neq 0$

---

# Modelo transformado

- Consideremos el modelo transformado de efectos fijos (comúnmente desviaciones con respecto a la media)

$$\tilde{y}_{it}=\tilde{X}_{it}+\tilde{\varepsilon}_{it}$$

- Podemos apilar las observaciones como

$$\tilde{y}_{i}=\tilde{X}_{i}+\tilde{\varepsilon}_{i}$$
---

# Variables instrumentales

- Siguiendo la lógica de VI en sección cruzada, buscamos instrumentos $Z_i$ que satisfacen $E(Z_i'\tilde{\varepsilon}_i)=0$

- Es decir, buscamos variables que no pertenezcan a la ecuación estructural y que estén correlacionadas con el regresor

- Implementamos directamente los estimadores de MGM vistos anteriormente

--

- Pero podemos tener más instrumentos usando regresores exógenos en periodos distintos al periodo contemporáno, usando los supuestos de exogeneidad débil o fuerte

- Notemos que en el modelo transformado las correlaciones relevantes son entr $Z_{is}$ y el error transformado $\tilde{\varepsilon}_{it}$

---

# Instrumentos para el modelo en desviaciones

- El modelo en desviaciones es

$$y_{it}-\bar{y}_i=(x_{it}-\bar{x}_i)'\beta+(\varepsilon_{it}-\bar{\varepsilon}_i)$$

- Supongamos exogeneidad débil, es decir que $E(z_{is}\varepsilon_{it})=0$ para $s\leq t$

- Por ejemplo, supongamos que $E(z_{is}\varepsilon_{it})\neq 0$ para algunos periodos $s>t$

- Entonces $\bar{\varepsilon}_i$ incluye valores del error que pueden estar correlaciondos con $z_{is}$

--

- **No** podemos usar usar VI si asumimos exogeneidad débil en el modelo within

- En el modelo within debemos asumir exogeneidad estricta

---

# Instrumentos para el modelo en diferencias

- El modelo en diferencias es

$$y_{it}-y_{it-1}=(x_{it}-x_{it-1})'\beta+(\varepsilon_{it}-\varepsilon_{it-1}),\quad\quad t=2,\ldots,T$$

- Si asumimos exogeneidad débil $E(z_{is}\varepsilon_{it})=0$ para $s\leq t$, entonces $E(z_{is}(\varepsilon_{it}-\varepsilon_{it-1}))=0$ para $s\leq t-1$

- Es decir, podemos usar $z_{it-1}, z_{it-2},\ldots$ como instrumentos

--

- $\beta$ queda estimado de forma consistente bajo exogeneidad débil

---

# Instrumentos para el modelo de efectos aleatorios

- Supongamos que tenemos instrumentos con $E(u_i|Z_i)=0$ y $V(u_i|Z_i=\Omega_i)$

- De manera análoga a como hicimos con el modelo de efectos aleatorios en una sección cruzada, podemos escribir el modelo transformado como

$$y_{it}-\hat{\lambda}\bar{y}_i=(x_{it}-\hat{\lambda}\bar{x}_i)'\beta+((1-\hat{\lambda})\alpha_i+(\varepsilon_{it}-\bar{\varepsilon}_i))$$
- Podemos estimar el modelo usando $(z_{it}-\hat{\lambda}\bar{z}_i)$ como instrumentos

--

- Este método solo puede ser usado bajo el supuesto de instrumentos con exogeneidad fuerte

---

# Resumen

- Podemos usar instrumentos en el sentido de sección cruzada (variables que no pertenecen a la ecuación estructural)

- Podemos usar los rezagos de los instrumentos (incluyendo a los regresores) como instrumentos adicionales

- Si asumimos un modelo de efectos aleatorios

  - Podemos estimar el modelo transformado asumiendo exogeneidad estricta
  
--

- Si asumimos un modelo de efectos fijos

  - Podemos asumir exogeneidad débil y estimar el modelo en diferencias
  
  - Podemos asumir exogeneidad estricta y estimar el modelo within

---

class: inverse, middle, center

# Panel dinámico

---

# Panel dinámico

- Modelo con efectos individuales y con el rezago de la variable dependiente como regresor

$$y_{it}=\gamma y_{it-1}+x_{it}'\beta+\alpha_i+\varepsilon_{it},\quad\quad i=1,\ldots,N,\quad t=1,\ldots,T$$
- Se asume independencia sobre $i$, $\gamma<1$ y errores serialmente no correlacionados

- Tenemos la complicación de que $y_{it-1}$ está correlacionado con el efecto fijo $\alpha_i$ por lo que estimar por MCO produce estimadores inconsistentes de $\gamma$ y $\beta$


---

# Fuentes de correlación

- Para ganar intuición, consideremos el modelo con $\beta=0$

$$y_{it}=\gamma y_{it-1}+\alpha_i+\varepsilon_{it},\quad\quad i=1,\ldots,N,\quad t=1,\ldots,T$$

- Si pudiéramos observar $\alpha_i$, condicionamos en $\alpha_i$ y estamos en el mundo de series de tiempo donde el interés recae en estimar $\gamma$

--

- Pero con $\alpha_i$ desconocida, al condicionar en el valor rezagado tenemos:

$$E(y_{it}|y_{it-1})=\gamma y_{it-1}+E(\alpha_i|y_{it-1})$$

- Más aún, la correlación es:

$$corr(y_{it},y_{it-1})=corr(\gamma y_{it-1}+\alpha_i+\varepsilon_{it},y_{it-1})$$
- Asumiendo que $corr(\varepsilon_{it},y_{it-1})=0$, la expresión anterior se convierte en

$$corr(y_{it},y_{it-1})=\gamma+corr(\alpha_i,y_{it-1})$$
---

# Fuentes de correlación

- Caso especial de efectos aleatorios: $\varepsilon_{it}\sim[0,\sigma^2_{\varepsilon}]$ y $\\alpha_i\sim[0,\sigma^2_{\alpha}]$

$$corr(y_{it},y_{it-1})=\gamma+\frac{1-\gamma}{1+\frac{\sigma^2_{\varepsilon}(1-\gamma)}{\sigma^2_{\alpha}(1+\gamma)}}$$
--

- **Dependencia de estado verdadera**: la correlación debida al mecanismo de persistencia de $y_{it-1}$ sobre $y_{it}$

  - Si $\alpha_i=0$, simplemente $corr(y_{it},y_{it-1})=\gamma$
  
  - Más generalmente, si 
  $\sigma^2_{\alpha}$ es muy pequeña con relación a $\sigma^2_{\varepsilon}$, entonces el denominador en la fracción es grande y la correlación se acerca a $\gamma$

--

- **Heterogeneidad no observada**: aún cuando $\gamma=0$, la correlación que se reduce a $corr(y_{it},y_{it-1})=\frac{\sigma^2_{\alpha}}{\sigma^2_{\alpha}+\sigma^2_{\varepsilon}}$


---

# Estimación

- MCO produce estimadores inconsistentes pues $y_{it-1}$ incluido como regresor es

$$y_{it-1}=\gamma y_{it-2}+\alpha_i+\varepsilon_{it-1}$$
es decir, está correlacionado con $\alpha_i$


--

- El estimador within también es inconsistente porque el modelo con desviaciones respecto a la media tiene a $(y_{it-1}-\bar{y}_{i,-1})$ como regresor

- Sin embargo, $y_{it-1}$ está correlacionado con $\varepsilon_{it-1}$ y por tanto con $\bar{\varepsilon}_i$

--

- El estimador de efectos aleatorios también es incosistente, como se mostró en el ejemplo con $\beta=0$

---

# Estimador de Arellano-Bond

- Consideremos el modelo en primeras diferencias y tres periodos de datos


$$y_{it}-y_{it-1}=\gamma(y_{it-1}-y_{it-2})+(x_{it-}-x_{it-1})'\beta+(\varepsilon_{it}-\varepsilon_{it-1}).\quad\quad t=2,\ldots,T$$

- Noten que $y_{it-1}$ puede usarse como instrumento de $(y_{it-1}-y_{it-2})$ pues no está correlacionado con el error transformado

--

- El **estimador de Arellano-Bond** propone usar todos los rezagos hasta $t$

- Las observaciones de los periodos 1 y 2 se pierden

- Para el periodo 3, solo $y_{i1}$ puede usarse como instrumento

- Para el periodo 4, se pueden usar $y_{i1}$ y $y_{i2}$

- Para el periodo 5, se pueden usar $y_{i1}$, $y_{i2}$ y $y_{i3}$

- También se pueden usar rezagos de $x_{it}$ como instrumentos adicionales

---

# Estimador de Arellano-Bond

- La matriz de instrumentos tendrá la forma

$$Z_i=\begin{pmatrix}z_{i3}' &  0 & \cdots & 0 \\0 &  z_{i4}' && \vdots \\\vdots & & \ddots & 0 \\0 & \cdots & 0 &z_{iT}'\\\end{pmatrix}$$
donde $z'_{it}=[y_{it-1},y_{it-3},\ldots,y_{i1},x'_{it-1}]$

- Y la estimación se realiza con los métodos de MGM vistos anteriormente

  - MGM en dos etapas (un paso)
  - MGM en dos pasos


---

# Próxima sesión

- Hablaremos sobre panel no lineal

  CT Capítulo 23

---

class: center, middle

Presentación creada usando el paquete [**xaringan**](https://github.com/yihui/xaringan) en R.

El *chakra* viene de [remark.js](https://remarkjs.com), [**knitr**](http://yihui.org/knitr), y [R Markdown](https://rmarkdown.rstudio.com).

Material de clase en versión preliminar.

**No reproducir, no distribuir, no citar.**
