---
title: "Modelos multinomiales"
author: "Irvin Rojas"
institute: "CIDE"
date: "3 de septimebre de 2020"
mathspec: true
output:
  xaringan::moon_reader:
    seal: false
    chakra: "https://remarkjs.com/downloads/remark-latest.min.js"
    lib_dir: libs
    nature:
      highlightLines: true
      countIncrementalSlides: false
      titleSlideClass: ["middle", "center"]
      ratio: "16:9"
      beforeInit: ["https://platform.twitter.com/widgets.js", "libs/cols_macro.js"]
      navigation:
      scroll: false
    css: [default, "libs/cide.css", metropolis-fonts, "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap-grid.min.css", "https://use.fontawesome.com/releases/v5.7.2/css/all.css", "https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css"]
include-before:
- '\newcommand\myeq{\stackrel{\mathclap{\normalfont\mbox{s}}}{~}}'

---
class: title-slide

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = "figures/")
library(tidyverse)
library(magick)
library(reticulate)

xfun::pkg_load2(c('base64enc', 'htmltools', 'mime'))
```

.title[
# Sesión 6. Modelos multinomiales
]
.subtitle[
## Econometría II
]
.author[
### Irvin Rojas <br> [rojasirvin.com](https://www.rojasirvin.com/) <br> [<i class="fab fa-github"></i>](https://github.com/rojasirvin) [<i class="fab fa-twitter"></i>](https://twitter.com/RojasIrvin) [<i class="ai ai-google-scholar"></i>](https://scholar.google.com/citations?user=FUwdSTMAAAAJ&hl=en)
]

.affiliation[
### Centro de Investigación y Docencia Económicas <br> División de Economía
]

---
# Agenda
  
1. Estudiaremos la generalización de los modelos de variable categórica a cuando las opciones son más de dos

1. Mostraremos las propiedades asintóticas de los estimadores de MV para este tipo de modelos


---

class: inverse, middle, center

# Modelos multinomiales

---

# Modelos multinomiales

- Pensemos en un caso más general donde $y$ toma el valor de $j$ si la $j$ésima alternativa se escoge:

$$p_j=P(y=j)\quad j=1,\ldots,m$$

- Esto se puede ver como un problema de $m$ decisiones binarias:

$$
y_i=
\begin{cases}
1 \quad\text{si }y=j \\
0 \quad\text{si }y\neq j \\
\end{cases}
$$

--

- La densidad multinomial para un individuo es

$$f(y)=p_1^{y_1}\times\ldots\times p_m^{y_m}=\prod_j p_j^{y_j}$$

donde $p_{ij}=P(y_i=j)=F_j(X_i,\beta)$

---

# Verosimilitud

- Para una muestra de $N$ observaciones independientes, la log verosimilitud es:

$$\mathcal{L}_n=\sum_i\sum_j y_{ij}\ln(p_{ij})$$

con $p_{ij}=F_j(x_i,\beta)$

--

- Las condiciones de primer orden están dadas por:

$$\frac{\partial \mathcal{L}}{\partial\beta}=\sum_i\sum_j\frac{y_{ij}}{p_{ij}}\frac{\partial p_{ij}}{\partial\beta}=0$$
---

# Distribución asintótica

- Noten que la distribución es necesariamente multinomial, por lo que $E(y_{ij})=p_{ij}$ y el estimador de MV será consistente

--

- Además, de forma análoga al modelo de probabilidad no lineal, la correcta especificación garantiza que la distribución asintótica esté dada por:

$$\hat{\beta}\stackrel{a}{\sim}\mathcal{N}\left(\beta_0, \left(\sum_i\sum_j\frac{1}{p_{ij}}\frac{\partial p_{ij}}{\partial\beta}\frac{\partial p_{ij}}{\partial\beta'}-\frac{\partial^2p_{ij}}{\partial\beta\partial\beta'}\Bigg|_{\beta_0} \right)^{-1}\right)$$
--

- De nuevo, con observaciones independientes sobre $i$, no es necesario implementar una matriz de sándwich

---

# Regresores variantes entre alternativas

- Podemos pensar la forma en que las $X$ entran en el modelo en dos extremos

- Pensemos en que cada alternativa tiene sus propias características

$$x_i=[x_{i1}'\;x_{i2}'\;\ldots\;x_{i1}']'$$
- Por tanto, la probabilidad de escoger la alternativa $j$ es:

$$p_{ij}=F_{ij}(x_i,\beta)=F_j(x_{i1}'\beta,\ldots,x_{im}\beta)$$

- Cuando esto sucede, las $\beta$s son constantes entre alternativas

- El modelo más común para este tipo de problemas es el **logit condicional**

---

# Regresores invariantes entre alternativas

- Por ejemplo, las características socioeconómicas de los consumidores que eligen entre varios tipos de cerveza

$$F_j(x_i,\beta)=F_j(x_i'\beta,\ldots x_i'\beta_m)$$

- En este caso, los parámetros son distintos para cada alternativa:

$$\beta=[\beta_1'\;\beta_2'\;\ldots\;\beta_m']$$

- Se realiza una normalización $\beta_1=0$

---

class: inverse, middle, center

# Logit multinomial

---

# Logit multinomial

- Es el modelo más popular para estudiar procesos multinomiales

- Se especializa a dos modelos específicos dependiendo de cómo son los regresores:

  - Logit condicional: regresores variantes entre alternativas
  
  - Logit multinomial: regresores invariantes entre alternativas


--

- En la práctica, podemos tener regresores de ambos tipos

  - Logit mixto
  


---

# Ejemplo: pesca 


| | $y = 1$|  $y = 2$| $y = 3$ | $y = 4$ | Todos $y$ |
|---- |:---: |:---: |:---: | :---:|:---: |
|Var. explicativa   | Playa | Puerto | Privado | Barco | 
|Ingreso (mUSD) |4.052| 3.387 | 4.654 | 3.881 | 4.099 | 
|Precio playa | 36 | 31 | 138 | 121 | 103 |
|Precio puerto ($)  | 36 | 31  | 138  | 121 | 103| 
|Precio privado ($) | 98  | 82 | 42 | 45 | 55|
|Precio barco ($) | 125|  110| 71| 75|  84 |
|Tasa de pesca playa | 0.28 | 0.26 | 0.21 | 0.25  | 0.24 |
|Tasa de pesca puerto | 0.22  | 0.20 | 0.13 | 0.16 | 0.16 |
|Tasa de pesca privado  |0.16 | 0.15 | 0.18 | 0.18 | 0.17 |
|Tasa de pesca barco | 0.52 | 0.50 | 0.65  | 0.69 | 0.63 |
|Probabilidad | 0.113 | 0.151 | 0.354 | 0.38 | 1.000 |
|N | 134| 178| 418| 452| 1182|

---

# Ejemplo: pesca 

- El precio de cada tipo y la tasa de pesca varían entre alternativas

- Parece haber una relación inversa entre el precio y la decisión

- La relación no es tan clara en cuanto a la tasa


--

- Además parece que la gente con mayor ingreso se mueve progresivamente hacia la derecha en la tabla anterior

---

# Logit condicional

- Supongamos que los regresores varían entre alternativas:

$$p_{ij}=\frac{exp(x_{ij}'\beta)}{\sum_{l=1}^m exp(x_{il}'\beta)},\quad j=1\ldots,m$$
- Esta expresión nos da la probabilidad de que el $i$ésimo individuo escoja la alternativa $j$

- Las probabilidades están entre 0 y 1 y suman 1

- En el **caso** del logit condicional, el signo del coeficiente $\beta$ es directamente interpretable

---

# Logit condicional en el problema de pesca

- En el caso del ejemplo de pesca, el logit condicional quedaría así:

$$p_{ij}=\frac{\beta_P P_{ij}+\beta_C C_{ij}}{\sum_{k=1}^4 exp(\beta_P P_{ik}+\beta_C C_{ik})},\quad j=1\ldots,4$$
- Lo que estimamos es el efecto en la probabilidad de escoger una alternativa cuando cambia el precio o cuando cambia la tasa de pesca

- En el caso del logit condicional, estaremos seguros que un aumento en el precio disminuye la probabilidad de elegir un modo de pesca

- Y lo contrario se concluye para la tasa de pesca

---

# Ejemplo: resultados del modelo de pesca 

| Regresor |  Tipo|  Coeficiente |  LC|  LMN |  Mixto | 
| ----- |  | :-----: | :-----: |  :-----: |  :-----:|  :-----: | 
 | Precio (P) |  Variante |  $\beta_P$ |  −0.021 |  –| −0.025 | 
 | Tasa de pesca (C) |  Variante |  $\beta_C$ |  0.953 |  –| 0.358 | 
 | Constante  | Invariante  | $\alpha_1$ : Playa  | –| 0.0 |  0.0 | 
 |  | | $\alpha_2$ : Puerto |  – |0.814 |  0.778 | 
 |  | | $\alpha_3$ : Privado |  –| 0.739 |  0.527 | 
 |  | | $\alpha_4$: Barco  | – |1.341  | 1.694 | 
 | Ingreso (I) |  Invariant|  $\beta_{I1}$ : Beach  | –| 0.0  | 0.0 | 
 |  | | $\beta_{I2}$ : Pier  | –  | −0.143 |  −0.128 | 
 |  | | $\beta_{I3}$ : Private  | –  | 0.092 |  0.089 | 
 |  | | $\beta_{I4}$ : Charter |– | −0.032  | −0.033 | 


---

# Logit multinomial

- La probablidad está dada por:

$$p_{ij}=\frac{exp(x_{i}'\beta_j)}{\sum_{l=1}^m exp(x_{i}'\beta_l)},\quad j=1\ldots,m$$

- Se impone la restricción de un $\beta_0$


- La interpretación de los parámetros es más complicada

- Un coeficiente estimado positivo no se traduce directamente como un incremento en la probabilidad de escoger una alternativa

- La interpretación de los coeficientes se da con respecto a la categoría base

---

# Logit multinomial en el problema de pesca

- El ingreso no varía entre alternativas

- En este caso el modelo logit multinomial queda como:

$$p_{ij}=\frac{exp(\alpha_j+\beta_{Ij}I_i)}{\sum_{k=1}^4exp(\alpha_k+\beta_{Ik}I_i)},\quad j=1\ldots,4$$

- Aquí normalizamos $\alpha_1=\beta_{I1}=0$

- En este caso, no podemos decir que un incremento en un regresor se traduzca en un incremento en la probabilidad de escoger cierta alternativa

- La interpretación en este modelo se da con respecto a la cateogría omitida, en este caso playa

---

class: inverse, middle, center

# Modelo mixto


---

# Modelo mixto

- Permite incorporar regresores variantes e invariantes entre alternativas

- La idea es escribir el modelo como un logit condicional, haciendo uso de variables dummy

---

# Próxima sesión

- Terminaré de hablar sobre el modelo multinomial

- Comenzaremos con conteo

  - CT capítulo 20
  
- Pequeños cambios al [calendario](https://github.com/rojasirvin/ECNII2020/blob/master/ECNII_calendario_otono_2020.pdf)

---

class: center, middle

Presentación creada usando el paquete [**xaringan**](https://github.com/yihui/xaringan) en R.

El *chakra* viene de [remark.js](https://remarkjs.com), [**knitr**](http://yihui.org/knitr), y [R Markdown](https://rmarkdown.rstudio.com).

Material de clase en versión preliminar.

**No reproducir, no distribuir, no citar.**